### PR TITLE
Client Daemon communication

### PR DESCRIPTION
**Pull request by Camerooooon**

### CODE REVIEW

**Comment by adamhutchings** [comment]
Looks good! Merging in a couple minutes.

**Comment by adamhutchings** [comment]
(I merely jest)

**Review by JakeRoggenbuck — DISMISSED** [review]
Nice!

**Comment by Camerooooon** [comment]
Not ready for merge at all.

**Comment by Sophon96** [comment]
huh

**Comment by Camerooooon** [comment]
This is being worked on in #62. Whoops miscommunication.

**Pull request closed without merging**
